version: '3'

services:
  fusion-ui:
    env_file:
      - .env
    build:
      context: .
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_AUTH_SERVICE_BASE_URL=${NEXT_PUBLIC_AUTH_SERVICE_BASE_URL}
        - NEXT_PUBLIC_AUTH_SERVICE_CLIENT_ID=${NEXT_PUBLIC_AUTH_SERVICE_CLIENT_ID}
        - NEXT_PUBLIC_AUTH_CALLBACK_URL=${NEXT_PUBLIC_AUTH_CALLBACK_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
    mem_limit: 256m
    environment:
      - NODE_ENV=production
    # 生产环境不需要挂载源代码，因为已在Dockerfile中复制了src目录
    # volumes:
    #  - ./src:/app/src 
