version: '3'

services:
  fusion-ui-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - NEXT_WEBPACK_USEPOLLING=1
    command: npm run dev:hot
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true 