version: '3'

services:
  fusion-ui:
    build: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=production
    # 生产环境不需要挂载源代码
    # volumes:
    #  - ./src:/app/src 