name: Deploy to Dev Server
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Pull latest code
        run: cd ~/project/fusion/fusion-ui && git pull
      - name: Build and deploy
        run: cd ~/project/fusion && docker compose up -d --build fusion-ui
      - name: Cleanup
        run: docker image prune -f
